[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[sources]
ProfileCanvas = {rev = "main", url = "https://github.com/pfitzseb/ProfileCanvas.jl"}

[compat]
JuliaFormatter = "1.0.0"
